---
- name: Install python-dev stuff, Nginx, supervisor, uswgi, aboutme webapp
  hosts: webservers
  remote_user: mtabara
  sudo: yes

  roles:
    - pythondevtools
    - supervisor-uwsgi
    - nginx
    - webapp

